server:
   port: 8080

spring:
    datasource:
         name: demo_db
         url: jdbc:mysql://127.0.0.1:3306/demo_db?serverTimezone=GMT%2B8&useUnicode=true&characterEncoding=utf8&useSSL=false&autoReconnect=true&failOverReadOnly=false&useOldAliasMetadataBehavior=true
         username: richardty
         password: 8888
         driver-class-name: com.mysql.cj.jdbc.Driver

    thymeleaf:
            cache: false

#mybatis:
#  mapper-locations: classpath:mapper/*.xml
#  type-aliases-package: com.example.demo.pojo

